"""
============================================================
CareConnect — ChromaDB Vector Service
Handles insertion and semantic retrieval of clinical notes
and medical documents using ChromaDB as the vector store.
============================================================
"""

import os
import uuid
import chromadb
from typing import List, Dict, Any
from config import settings

# Initialize ChromaDB Persistent Client
_chroma_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "chroma_data")
_client = chromadb.PersistentClient(path=_chroma_path)

# Create or get the main collection
# We use cosine similarity which is standard for Google embeddings
_collection = _client.get_or_create_collection(
    name="clinical_records",
    metadata={"hnsw:space": "cosine"}
)

def add_record(patient_id: str, text: str, embedding: List[float], doc_type: str = "clinical_note") -> str:
    """
    Insert a document and its embedding into ChromaDB.
    
    Args:
        patient_id: MongoDB ObjectId string to link this record to a patient
        text: The raw text content of the note or document
        embedding: The vector embedding generated by the LLM
        doc_type: String identifier like 'clinical_note' or 'medical_document'
        
    Returns:
        The generated UUID for the inserted record.
    """
    try:
        record_id = str(uuid.uuid4())
        
        # ChromaDB requires IDs to be strings
        _collection.add(
            ids=[record_id],
            documents=[text],
            embeddings=[embedding],
            metadatas=[{
                "patientId": str(patient_id),
                "type": doc_type
            }]
        )
        print(f"📥 Inserted record into ChromaDB for patient {patient_id}")
        return record_id
    except Exception as e:
        print(f"⚠️  ChromaDB insertion failed: {e}")
        return ""

def query_records(patient_id: str, query_embedding: List[float], top_k: int = 5) -> List[Dict[str, Any]]:
    """
    Perform a vector search to find relevant context for a patient.
    
    Args:
        patient_id: Filters results to only this patient (prevents data leakage)
        query_embedding: The vector for the user's question
        top_k: Number of chunks to retrieve
        
    Returns:
        List of dictionaries containing the text and metadata.
    """
    try:
        results = _collection.query(
            query_embeddings=[query_embedding],
            n_results=top_k,
            where={"patientId": str(patient_id)} # Strict filter
        )
        
        # Chroma returns lists of lists (since we queried 1 embedding, we take the 0th index)
        chunks = []
        if results and results.get("documents") and len(results["documents"]) > 0:
            docs = results["documents"][0]
            metadatas = results["metadatas"][0]
            
            for i in range(len(docs)):
                chunks.append({
                    "text": docs[i],
                    "type": metadatas[i].get("type", "unknown"),
                    "date": "recent" # Chroma doesn't natively auto-timestamp, so we just supply context
                })
                
        print(f"🔎 ChromaDB returned {len(chunks)} chunks for patient {patient_id}")
        return chunks
        
    except Exception as e:
        print(f"⚠️  ChromaDB query failed: {e}")
        return []
